package model;
// Generated Mar 24, 2026, 1:12:41 AM by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	@Id
	@Column(name = "CUS_ID")
	private Integer cusId;

	@Column(name = "NAME")
	private String name;

	@Column(name = "SURNAME")
	private String sername;

	@Column(name = "username")
	private String username;

	private String pwd;

	@Column(name = "USERROLES")
	private String userroles;

	@OneToMany(mappedBy = "customer", cascade = CascadeType.ALL, fetch = FetchType.EAGER)
	private Set<Phonenumber> phonenumbers = new HashSet<>(0);

	public Customer() {
	}

	public Customer(String username, String pwd) {
		this.username = username;
		this.pwd = pwd;
	}

	public Customer(String name, String sername, String username, String pwd, String userroles, Set phonenumbers) {
		this.name = name;
		this.sername = sername;
		this.username = username;
		this.pwd = pwd;
		this.userroles = userroles;
		this.phonenumbers = phonenumbers;
	}

	public Customer(String name, String username, String pwd, Set<Phonenumber> phonenumbers) {
		this.name = name;
		this.username = username;
		this.pwd = pwd;
		this.phonenumbers = phonenumbers;
	}

	public void addPhonenumber(Phonenumber ph) {
		// 1. ตรวจสอบก่อนว่า Set ของเราเป็น null หรือไม่ (ถ้าเป็น null ให้สร้างใหม่)
		if (this.phonenumbers == null) {
			this.phonenumbers = new HashSet<Phonenumber>(0);
		}

		// 2. Set Both Sides (ความสัมพันธ์แบบสองฝั่ง)
		// ฝั่ง Phonenumber: ให้รู้ว่าใครเป็นเจ้าของ (Customer)
		ph.setCustomer(this);

		// ฝั่ง Customer: เพิ่มเบอร์เข้าไปในรายการ (Set)
		this.phonenumbers.add(ph);
	}

	public Integer getCusId() {
		return this.cusId;
	}

	public void setCusId(Integer cusId) {
		this.cusId = cusId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSername() {
		return this.sername;
	}

	public void setSername(String sername) {
		this.sername = sername;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	public String getUserroles() {
		return this.userroles;
	}

	public void setUserroles(String userroles) {
		this.userroles = userroles;
	}

//	public Set getPhonenumbers() {
//		return this.phonenumbers;
//	}
//
//	public void setPhonenumbers(Set phonenumbers) {
//		this.phonenumbers = phonenumbers;
//	}

	public Set<Phonenumber> getPhonenumbers() {
		return phonenumbers;
	}

	public void setPhonenumbers(Set<Phonenumber> phoneNumbers) {
		this.phonenumbers = phoneNumbers;
	}

}
